### ISSUE TITLE
Stego image question

### ISSUE THREAD

**Issue by ZhangJH66** [vvictoryuki/CRoSS#1]
`

    latent_noise = ode.invert(prompt_1, image_gt_latent, is_forward=True)
    image_hide_latent = ode.invert(prompt_2, latent_noise, is_forward=False)

    # save container image
    image_hide = ode.latent2image(image_hide_latent)
    cv2.imwrite("{:s}/hide.png".format(args.save_path), cv2.cvtColor(image_hide, cv2.COLOR_RGB2BGR))
    
    # reveal process
    latent_noise = ode.invert(rev_prompt_2, image_hide_latent, is_forward=True)

    image_reverse_latent = ode.invert(rev_prompt_1, latent_noise, is_forward=False)
    image_reverse = ode.latent2image(image_reverse_latent)`
`

In this piece of code, it seems like you are directly using the latent vector (1\*4\*64\*64) that has not gone through vae.decoder for secret message extraction. In the concept of image steganography, we should use the image generated after vae.decoder (e.g. 1\*3\*512\*512) as the secret message container.

As in the following code: 

`

    latent_noise = ode.invert(prompt_1, image_gt_latent, is_forward=True)
    image_hide_latent = ode.invert(prompt_2, latent_noise, is_forward=False)

    # save container image
    image_hide = ode.latent2image(image_hide_latent)
    cv2.imwrite("{:s}/hide.png".format(args.save_path), cv2.cvtColor(image_hide, cv2.COLOR_RGB2BGR))
    
    hide_latent_for_reveal = ode.image2latent(image_hide)

    # reveal process
    latent_noise = ode.invert(rev_prompt_2, hide_latent_for_reveal, is_forward=True)

    image_reverse_latent = ode.invert(rev_prompt_1, latent_noise, is_forward=False)
    image_reverse = ode.latent2image(image_reverse_latent)`
`

**Comment by xuanyuzhang21** [comment]
Thank you for the reminder! we uploaded the wrong version of the code. It has now been corrected in [demo.py](https://github.com/vvictoryuki/CRoSS/blob/main/demo.py).
